### ISSUE TITLE
YouTube Video Playback

### ISSUE THREAD

**Issue by webternals** [vassbo/freeshow#28] opened 2022-06-17 15:41 UTC
First I can't get any video other than the one you have included in the Example to work. Every other video gives a Video Unavailable Watch on YouTube message.

Second when ever you play the video and try and go to the next shows slide the video stays and you are required to click Clear all to get the video to go away.

**Comment by vassbo** [comment] 2022-06-17 16:04
Hey, thanks for writing.

For the videos I think the problem might be if you are using the "https://youtu.be/" prefix. It should work if you just paste the ID in the URL (the last 11 chars). If that's the case it will be fixed in the next version.

Secondly, the video is a "background" meaning it is a feature that you can have text slides on top over the video. But if you press F1 or the "Clear background" button (The image icon right under the "Clear all" button), you can clear just the video.

**Comment by webternals** [comment] 2022-06-17 16:10
Actually it does not matter if I use URL or video ID. I have tried several different videos. I thought the same thing you did about the URL vs ID so I tried it different ways.

**Comment by vassbo** [comment] 2022-06-17 16:14
Hmm, weird. Could you send a screenshot of your screen when you get the unavailable message?

**Comment by vassbo** [comment] 2022-06-18 07:10
I looked a bit more into it, and I found out that some videos are working fine and some show a "Video Unavailable" message, because the creator has diabled embeds for the video. The weird part is that all videos work fine in my dev space because it is a localhost server, so maybe it's possible to do something about it.

I found this related issue (might not be relevant for you): https://stackoverflow.com/questions/52856299/youtube-videos-not-played-in-electron-app-but-in-a-website-does

**Comment by playmepe** [comment] 2022-07-01 19:37
los videos desde algunas listas no funciona como https://youtu.be/y3tyQqjS4qY?list=RDEMJdzEY8zpIjdRLVtM-fSoJA pero otras listas si funcionan como https://youtu.be/v286FcaCNhc?list=RDhbXgvM-y0ng

**Comment by vassbo** [comment] 2022-07-02 07:17
Thanks @playmepe. If you click share on the video and copy that URL instead of copying the browser URL it should work for all the videos in the playlists you linked to. The reason is because your URLs were ending with ?list=...
I will just check for that and remove it so it should work better in the next update.

**Comment by playmepe** [comment] 2022-07-11 02:10
Ahora funciona bién. Será posible crear una lista y reproducir en forma continua?

**Comment by vassbo** [comment] 2022-07-11 17:04
@playmepe Good. You can create lists, and swap between with the arrow down/up keys. But continuous mode is not yet available, but might be in the future.

**Comment by vassbo** [comment] 2023-02-12 19:49
I'm going to close this issue until there is a solution.
I have looked a bit more and there don't seem to be a fix right now, sorry @webternals.

Here are some links for future reference:
- https://stackoverflow.com/questions/52856299/youtube-videos-not-played-in-electron-app-but-in-a-website-does
- https://stackoverflow.com/questions/53442605/youtube-video-playing-on-browser-but-not-on-electron-js-app
- https://stackoverflow.com/questions/51424578/embed-youtube-code-is-not-working-in-html
- https://stackoverflow.com/questions/59532941/embeded-youtube-video-not-available-in-iframe-html

**Closed by vassbo** 2023-02-12 19:49 UTC
Labels: bug
